### ISSUE TITLE
Errors on p. 19?

### ISSUE THREAD

**Issue by mtift** [smach/R4JournalismBook#1]
Loving the book!

At the very bottom of p. 19, it says, "the fifth line creates the graph" but I only see three lines?

Then, on the last line it reads "sfdata, tells dygraph what data set to graph" -- should sfdata be sfincome?

**Comment by smach** [comment]
Thank you, and thanks for letting me know about the error! Story about that - I'd written that part of the book awhile ago. After editing, when I had one last chance to look things over before it went to print, I realized that packages had changed and I should update the code. Unfortunately, I didn't catch everything in the text, and that part didn't get edited again. As I often say at work, "everyone needs an editor." I'll add that to the book Web site update page.

**Comment by smach** [comment]
OK that's been added to the book's [additions and corrections page](https://smach.github.io/R4JournalismBook/Updates.html). Thanks again for taking the time to let me know!
