### ISSUE TITLE
Book files for chapter 5 HTTP error 404

### ISSUE THREAD

**Issue by grace-spitzer-wong** [smach/R4JournalismBook#3]
Hi

I'm not able to download the files for the book from the Github site:
https://github.com/smach/R4JournalismBook/archive/master.zip

I get this error message after running usethis:
√ Downloading from 'https://github.com/smach/R4JournalismBook/archive/master.zip'
x HTTP error 404.
  Download failed :(
  See above for everything we know about why it failed.
  Shall we try a couple more times, with a longer timeout?

A 404 error also shows when I check the page itself.
Has the URL changed?

**Comment by smach** [comment]
Hi sorry @Grace-W I was off my GitHub-related email account for a few days. Do you have what you need? To institute more inclusive language, I changed the main branch of this repository from "master" to "main", but that affects instructions in the book. I will add an explanation on the main page here.

**Comment by grace-spitzer-wong** [comment]
Hi Sharon

Thanks for getting in touch - I found an alternate way to access the files. Sorry for not replying sooner as I haven't been checking my work emails as I'm on leave.

All is good and thank you for such a relevant and great book.

Thanks
