### ISSUE TITLE
suggested replacement for read_shape() function in Chapter 11's mapping exercise?

### ISSUE THREAD

**Issue by lisawilliams** [smach/R4JournalismBook#4]
Hello! I am learning so much from Practical R for Mass Communication & Journalism. I've been working my way through the book and have gotten to Chapter 11, the one on maps. 

It looks like the tmap package no longer has the read_shape() as a function. Is there a function from another package that could be slotted into the exercises in Chapter 11?

**Comment by smach** [comment]
I'm glad you're finding the book useful!

Give the sf package's st_read() a try.

Best,
Sharon

**Comment by lisawilliams** [comment]
It worked! Thanks so much.

**Comment by smach** [comment]
Great!
